# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Ansys Material Database - single-file exe."""

from pathlib import Path

block_cipher = None
ROOT = Path(SPECPATH)

a = Analysis(
    [str(ROOT / 'run_packaged.py')],
    pathex=[str(ROOT / 'src')],
    binaries=[],
    datas=[],
    hiddenimports=[
        # --- Core app modules ---
        'ansys_material_db',
        'ansys_material_db.app',
        'ansys_material_db.i18n',
        'ansys_material_db.main',
        'ansys_material_db.config',
        'ansys_material_db.config.settings',
        'ansys_material_db.core',
        'ansys_material_db.core.document_parser',
        'ansys_material_db.core.knowledge_base',
        'ansys_material_db.core.property_extractor',
        'ansys_material_db.core.qa_engine',
        'ansys_material_db.core.xml_generator',
        'ansys_material_db.data',
        'ansys_material_db.data.database',
        'ansys_material_db.data.embeddings',
        'ansys_material_db.data.llm_client',
        'ansys_material_db.gui',
        'ansys_material_db.gui.main_window',
        'ansys_material_db.gui.material_browser',
        'ansys_material_db.gui.property_editor',
        'ansys_material_db.gui.document_manager',
        'ansys_material_db.gui.export_page',
        'ansys_material_db.gui.export_dialog',
        'ansys_material_db.gui.settings_page',
        'ansys_material_db.gui.settings_dialog',
        'ansys_material_db.gui.xml_viewer_page',
        'ansys_material_db.gui.xml_import_dialog',
        'ansys_material_db.gui.import_wizard',
        'ansys_material_db.gui.styles',
        'ansys_material_db.gui.qa_chat_panel',
        'ansys_material_db.gui.widgets',
        'ansys_material_db.gui.widgets.property_table',
        'ansys_material_db.gui.widgets.chat_bubble',
        'ansys_material_db.gui.widgets.temp_curve_widget',
        'ansys_material_db.models',
        'ansys_material_db.models.material',
        'ansys_material_db.models.document',
        'ansys_material_db.models.chat',
        # --- Third-party (often missed by PyInstaller) ---
        'fitz',               # PyMuPDF
        'fitz.fitz',          # PyMuPDF internals
        'PIL',
        'PIL.Image',
        'PIL.ImageFont',
        'PIL.ImageDraw',
        'pytesseract',
        'openai',
        'openai._base_client',
        'openai._utils',
        'openai.lib',
        'openai.lib.streaming',
        'lxml',
        'lxml.etree',
        'lxml._elementpath',
        'numpy',
        'sentence_transformers',
        'sentence_transformers.SentenceTransformer',
        'sentence_transformers.models',
        'torch',
        'torch.nn',
        'torch._C',
        'huggingface_hub',
        'tokenizers',
        'tokenizers.models',
        'tokenizers.normalizers',
        'tokenizers.pre_tokenizers',
        'tokenizers.processors',
        'transformers',
        'transformers.models',
        'transformers.models.bert',
        'transformers.models.bert.tokenization_bert',
        'regex',
        'tqdm',
        'filelock',
        'fsspec',
        'pydantic',
        'pydantic.main',
        'httpx',
        'jinja2',
        'colorama',
        'requests',
        # --- PyQt6 plugin support ---
        'PyQt6.sip',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtSvg',
        'PyQt6.QtNetwork',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'scipy', 'pandas',
        'IPython', 'notebook', 'jupyter', 'test',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AnsysMaterialDB',
    icon='app_icon.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)